name: Deploy to Staging

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: adalmia/sensai-ai:v2-dev
          build-args: |
            S3_BUCKET_NAME=dev-sensai-ind
            S3_FOLDER_NAME=dev
            ENV=staging
            BUGSNAG_API_KEY=${{ secrets.BUGSNAG_API_KEY_STAGING }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_STAGING }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID_STAGING }}
            PHOENIX_ENDPOINT=${{ secrets.PHOENIX_ENDPOINT }}
            PHOENIX_API_KEY=${{ secrets.PHOENIX_API_KEY_STAGING }}
