name: Deploy to Staging

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: adalmia/sensai-ai:v2-dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            S3_FOLDER_NAME=${{ secrets.S3_FOLDER_NAME }}
            ENV=${{ secrets.ENV }}
            BUGSNAG_API_KEY=${{ secrets.BUGSNAG_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            PHOENIX_ENDPOINT=${{ secrets.PHOENIX_ENDPOINT }}
            PHOENIX_API_KEY=${{ secrets.PHOENIX_API_KEY }}
            SLACK_USER_SIGNUP_WEBHOOK_URL=${{ secrets.SLACK_USER_SIGNUP_WEBHOOK_URL }}

      - name: Notify Slack on Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          webhook_url: ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK_URL }}
          text: "🚀 Staging deployment completed successfully!"
          fields: repo,message,commit,author,action,eventName,ref,workflow

      - name: Notify Slack on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          webhook_url: ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK_URL }}
          text: "❌ Staging deployment failed!"
          fields: repo,message,commit,author,action,eventName,ref,workflow
